# Generated by Django 6.0.7 on 2026-07-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Номер телефона"),
        ),
    ]
