# Generated by Django 6.0.7 on 2026-08-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_managers_user_date_joined_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="link",
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату"),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name="id сессии"),
        ),
    ]
