# Generated by Django 6.0.7 on 2026-08-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_payments_link_payments_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="link",
            field=models.URLField(blank=True, max_length=800, null=True, verbose_name="Ссылка на оплату"),
        ),
        migrations.AlterField(
            model_name="payments",
            name="session_id",
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name="id сессии"),
        ),
    ]
