services:
  db:
    image: postgres:17
    container_name: postgres_db
    env_file:
      - ./.env
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 30s

  redis:
    image: redis:7
    restart: unless-stopped
    container_name: redis
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: django_migrate
    command: python manage.py migrate
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: materials
    env_file:
      - ./.env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    depends_on:
      migrate:
        condition: service_completed_successfully

  nginx:
    build:
      context: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: celery_worker
    command: celery -A config worker -l INFO -P gevent
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: celery_beat
    command: celery -A config beat -l INFO
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      celery:
        condition: service_started

volumes:
  postgres_data:
  redis_data:
  static_volume: