# Generated by Django 6.0.7 on 2026-07-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Название урока"),
        ),
    ]
