# Generated by Django 6.0.7 on 2026-08-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="video",
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Видео урока"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Видео урока"),
        ),
    ]
