# Generated by Django 6.0.7 on 2026-08-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0009_alter_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="update_datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата обновления курса"),
        ),
    ]
