# Generated by Django 6.0.7 on 2026-08-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0010_course_update_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="update_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="Дата обновления курса"),
        ),
    ]
